# Generated by Django 4.1.2 on 2022-10-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_alter_fcuser_level_alter_fcuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='level',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=8, verbose_name='등급'),
        ),
    ]
